### ISSUE TITLE
Example with Multiple dispatches has error in the runtime

### ISSUE THREAD

**Issue by nirvedhmeshram** [nod-ai/iree-amd-aie#177] opened 2024-02-20 15:46 UTC
Please refer to this log where the CI captures this issue
https://gist.github.com/nirvedhmeshram/218ce409d5e26d390d053cfc74419fa4

To reproduce, you can run these CI actions locally,
https://github.com/nod-ai/iree-amd-aie/blob/main/.github/workflows/ci.yml#L102-L110

To cause the issue you will need the change done by https://github.com/nod-ai/iree-amd-aie/pull/176

**Comment by nirvedhmeshram** [comment] 2024-02-20 15:46
cc @MaheshRavishankar

**Comment by daveliddell** [comment] 2024-02-24 02:15
The problem is that during compilation of the two executables, which happens in parallel, some of the intermediate files have the same name, so the compilations step on each other.

Fixed in pending PR https://github.com/nod-ai/iree-amd-aie/pull/181

The fix makes separate subdirectories for each executable.

**Closed** 2024-02-26 22:23 UTC
