### ISSUE TITLE
Building peano -- lld related error 

### ISSUE THREAD

**Issue by newling** [nod-ai/iree-amd-aie#408] opened 2024-06-11 18:55 UTC
Using the build commands suggested for building peano as part of the iree-amd-aie flow (see playbook)

```
cd ..
git clone https://gitenterprise.xilinx.com/XRLabs/llvm-aie.git
cd llvm-aie

cmake -G Ninja -S llvm -B ../llvm-build -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_INSTALL_PREFIX=../install -DLLVM_ENABLE_PROJECTS="clang;lld" \
  -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="X86;AIE" \
  -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_ENABLE_LLD=ON \
  -DLLVM_ENABLE_RUNTIMES="compiler-rt;libc" \
  -DLLVM_BUILTIN_TARGETS="aie2-none-unknown-elf;aie-none-unknown-elf" \
  -DLLVM_RUNTIME_TARGETS="aie-none-unknown-elf;aie2-none-unknown-elf" \
  -DBUILTINS_aie-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DBUILTINS_aie-none-unknown-elf_CMAKE_BUILD_TYPE=Release \
  -DRUNTIMES_aie-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DRUNTIMES_aie-none-unknown-elf_CMAKE_BUILD_TYPE=Release \
  -DBUILTINS_aie2-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DBUILTINS_aie2-none-unknown-elf_CMAKE_BUILD_TYPE=Release \
  -DRUNTIMES_aie2-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DRUNTIMES_aie2-none-unknown-elf_CMAKE_BUILD_TYPE=Release \
  -DLLVM_LIBC_FULL_BUILD=ON

cmake --build ../llvm-build --target install
```

I hit problems building the most recent version of llvm-aie (aka peano). 

The following commit builds. It the the most recent commit I have successfully built. (Does not build on first attempt, need a few runs of the cmake commands above, but gets there eventually) 

```
commit d3021c944de13e72dbe1e653d9866aec43460bc0
Author: Sagar Maheshwari <sagar.maheshwari@amd.com>
Date:   Fri May 31 00:50:04 2024 +0530

    [AIE2] Suppress unused variable warning.
```

The following does not build. It is the first commit after the above commit which fails to build. It's not clear what's in the commit below which makes my build fail

```
commit 70703e80a6ecf8f8cf3fa724191dd1f36951dea3 (HEAD)
Author: mchokshi091101 <mchokshi@amd.com>
Date:   Wed May 29 20:01:21 2024 +0530

    [AIE2] Driver changes for startup objects
```

The error is:
      
```
CMake Error at /proj/gdba/jamesn/workspace/peano/llvm-aie/llvm/cmake/modules/HandleLLVMOptions.cmake:365 (message):
  Host compiler does not support '-fuse-ld=lld'.  Please make sure that 'lld'
  is installed and that your host compiler can compile a simple program when
  given the option '-fuse-ld=lld'.
Call Stack (most recent call first):
  CMakeLists.txt:156 (include)
```

Note that there has already been alot of LLVM built at this point: It seems like there is a second run of cmake configuration after the majority of LLVM has been built. 

Adding more print statements in HandleLLVMOptions.cmake, I narrow the problem down as follows:

Trying to compile foo.cpp with combinations of clang++ and lld:
```
int main() { return 0; }
```

Using the lld built with peano:
/proj/gdba/jamesn/workspace/peano/llvm-build/bin/clang++ -fuse-ld=/proj/gdba/jamesn/workspace/peano/llvm-build/bin/lld foo.cpp
```
lld is a generic driver.
Invoke ld.lld (Unix), ld64.lld (macOS), lld-link (Windows), wasm-ld (WebAssembly) instead
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Using the lld in system works:
jnewling@xsjipunuc50:/proj/gdba/jamesn/workspace/peano/llvm-aie $  /proj/gdba/jamesn/workspace/peano/llvm-build/bin/clang++ -fuse-ld=lld foo.cpp

Using ld.lld with peano works:
/proj/gdba/jamesn/workspace/peano/llvm-build/bin/clang++ -fuse-ld=/proj/gdba/jamesn/workspace/peano/llvm-build/bin/ld.lld foo.cpp

So should we be replacing lld with ld.lld somewhere?

**Comment by makslevental** [comment] 2024-06-11 22:42
This is just saying that lld isn't installed on wherever you're compiling. You could just drop `-DLLVM_ENABLE_LLD=ON` at the cost of a longer link time but probably just install lld on whatever system (I prefer that rather than boostrapping).

**Comment by newling** [comment] 2024-06-12 03:37
I'm not sure it's saying lld isn't installed, seems like something else to me. 

Fine:
```
./peano/llvm-build/bin/clang++ -fuse-ld=lld foo.cpp
```

Fine:
```
./peano/llvm-build/bin/clang++ -fuse-ld=./peano/llvm-build/bin/ld.lld foo.cpp
```

Not good, errors with `lld is a generic driver. `
```
./peano/llvm-build/bin/clang++ -fuse-ld=./peano/llvm-build/bin/lld foo.cpp
```

Seems like there's something funky with the lld which is built with peano.

**Comment by konstantinschwarz** [comment] 2024-06-12 09:04
The problem is caused by
```
-DRUNTIMES_aie2-none-unknown-elf_LLVM_USE_LINKER=lld \
```
This triggers a linker check in the runtimes build, which tries to compile & link a basic test. That fails because the compiler driver adds the startup files to the linker invocation, but we are actually building those files as part of the runtimes build.

We have a CMake cache for building Peano at https://github.com/Xilinx/llvm-aie/blob/aie-public/clang/cmake/caches/Peano-AIE.cmake, which you can use in your CMake configure step:

```
cmake -G Ninja -S llvm -B ../llvm-build  \
  -DCMAKE_INSTALL_PREFIX=../install -DLLVM_ENABLE_PROJECTS="clang;lld" \
  -DLLVM_BUILD_EXAMPLES=ON \
  -C clang/cmake/caches/Peano-AIE.cmake
cmake --build ../llvm-build --target install
```

**Comment by newling** [comment] 2024-06-12 16:27
Thanks @konstantinschwarz  -- I can confirm after removing the lines

```
  -DBUILTINS_aie-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DRUNTIMES_aie-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DBUILTINS_aie2-none-unknown-elf_LLVM_USE_LINKER=lld \
  -DRUNTIMES_aie2-none-unknown-elf_LLVM_USE_LINKER=lld \
```

the build works. Do you recommend that we just use:

```
cmake -G Ninja -S llvm -B ../llvm-build  \
  -DCMAKE_INSTALL_PREFIX=../install -DLLVM_ENABLE_PROJECTS="clang;lld" \
  -DLLVM_BUILD_EXAMPLES=ON \
  -C clang/cmake/caches/Peano-AIE.cmake
cmake --build ../llvm-build --target install
```

i.e. does the line ` -C clang/cmake/caches/Peano-AIE.cmake`  set the configuration flags as we probably wan't them?

**Comment by makslevental** [comment] 2024-06-12 16:30
> i.e. does the line  -C clang/cmake/caches/Peano-AIE.cmake set the configuration flags as we probably want them?

Yes that's actually exactly what `-C` does (as I recently learned) - it "presets" cmake cache to the values in the "script".

**Comment by newling** [comment] 2024-06-12 17:50
OK. good to know. Works for me

```
cmake -G Ninja -S llvm -B ../llvm-build -DCMAKE_INSTALL_PREFIX=../install -DLLVM_ENABLE_PROJECTS=clang;lld -DLLVM_BUILD_EXAMPLES=ON -C clang/cmake/caches/Peano-AIE.cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release
```

I'll update the instructions we have in the playbook (FYI @daveliddell)

**Comment by newling** [comment] 2024-06-12 19:40
I have another issue using peano (and again I'm not sure if the issue is in iree-amd-aie, mlir-aie, or llvm-aie, or my configuration): https://github.com/nod-ai/iree-amd-aie/issues/411 

I'm still investigating but @makslevental and @konstantinschwarz  if you have any ideas that might speed my investigations up, please let me know!

**Comment by konstantinschwarz** [comment] 2024-06-13 15:19
I found that passing `-DLLVM_ENABLE_LLD=ON` to the build of **Peano** is also forwarded to the runtime library build, triggering the same CMake check. I pushed a fix for this here: https://github.com/Xilinx/llvm-aie/pull/75
That allows to still link Peano itself using LLD, improving overall build time

>i.e. does the line  -C clang/cmake/caches/Peano-AIE.cmake set the configuration flags as we probably want them?

Yes I'd recommend to use that CMake cache to set most options.
You can still pass `-D...` options on the command line if you want to add additional options, or overrule any options set in Peano-AIE.cmake

**Closed** 2024-07-26 19:02 UTC
